apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx2-vaibhav
    image: nginx:1.27.1
    ports:
    - containerPort: 8080
  - name: watcher
    image: afakharany/watcher